name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r agents/requirements.txt
          pip install pytest pytest-asyncio black ruff mypy

      - name: Lint with ruff
        run: ruff agents --exit-zero

      - name: Format check with black
        run: black --check agents

      - name: Type check with mypy
        run: mypy agents || true  # non-blocking for now

      - name: Test with pytest
        env:
          OPENAI_API_KEY: dummy
        run: pytest agents/tests -q 